add doc on %attribute and templates
swig/swig pull request #2224
Opened 2022-03-04 07:43 UTC by KrisThielemans

Documents how to use `%attribute` with templates. Addresses #2142.

@ojwb does this look ok? Apologies for the multiple commits. Not a good idea to try to do this via GitHub's edit feature... Please squash-merge if it's fine.

2022-03-04 19:02 UTC, wsfulton requested changes
Could you please use the SWIG coding style wrt braces and ref placement. Am also confused as you mention instantiating the template but there is no instantiation!

2022-03-04 19:20 UTC, ojwb commented on Doc/Manual/Library.html
> +<li><a href="#Library_attribute_templates">&percnt;attribute and C++ templates</a></li>
The rest of the manual just uses a literal `%`.

2022-03-04 19:24 UTC, ojwb commented on Doc/Manual/Library.html
> +This means that it has to be repeated if you want to use different instantiations.
Seems to be missing a `<p>`...`</p>` block.

2022-03-04 19:36 UTC, ojwb commented
> Could you please use the SWIG coding style wrt braces and ref placement. Am also confused as you mention instantiating the template but their is no instantiation!

IIUC the point to make is that you need to say `A<int>` not `A<T>` or just `A`.  As you note that isn't really "instantiating".  I couldn't think what the correct term was, but looking at https://en.cppreference.com/w/cpp/language/templates it seems to be "template-id".  Not sure how many people will understand that (I wouldn't have until I went and looked) especially as the audience probably include people who aren't really C++ coders.  I guess we could say something like "template-id (i.e. `A<int>` not `A<T>` or just `A`)" to clarify what's meant for people who don't know the term.

2022-03-04 19:38 UTC, ojwb commented
> Apologies for the multiple commits. Not a good idea to try to do this via GitHub's edit feature... Please squash-merge if it's fine.

Yeah, Github's edit feature is really better avoided except for really simple stuff like trivial typos in docs.  Not a big problem though - can squash to merge once it's ready.

And thanks for following through with a patch.

2022-03-06 11:54 UTC, KrisThielemans commented
Hopefully ok now. let me know.

2022-03-06 17:34 UTC, merged