Eliminate T_ERROR
swig/swig pull request #2643
Opened 2023-06-23 04:20 UTC by ojwb

This was only being used in one very specific case where we failed to parse a type string, which seems like it really is just an internal error so try handling it as such.

2023-06-23 05:36 UTC, ojwb commented
@wsfulton Thoughts?

I'm not seeing how we could ever get `T_ERROR` as the type code without a broken type string, which seems like it's an internal consistency error to me.  Digging back in the history it looks like it's been like this since before the start of version control.

It does seem weird that we have these two warnings that probably can't actually be triggered.  I wonder if they should actually be hooked up to cases where we don't know the type of the value (something like `$N.val == NULL` maybe).  I tried this example to see what happens and currently it wraps `x`, and seems to assume `foo()` returns `int` (which I suppose is reasonable for C at least):

```
%module x
%constant x = foo();
```

Maybe there's a better example where we don't know the type and it isn't useful to assume it's `int` though.

2023-06-23 21:19 UTC, ojwb commented
Poking git history harder, it actually looks like the last place that set `T_ERROR` aside from the type-string parser error case was removed in 2004 by ad39b124c8f4f9faeb6ae6da37dd1de4100dbd6f.

2023-06-24 11:20 UTC, wsfulton requested changes
I like this change - malformed SwigType are an internal error and should never occur.

2023-06-24 11:20 UTC, wsfulton commented on Source/CParse/parser.y
> +		 Setattr($$,"name",$2);
Suggest whitespace fixes (spaces after the comma) given other whitespace indentation change on this line and others.

2023-06-24 21:01 UTC, closed without merging