[python, ruby] Add Director guard file with C++ 11 std::mutex
swig/swig pull request #2870
Opened 2024-04-11 20:20 UTC by erezgeva

Follow #2861

Add a common file for python and Ruby.
Remove unused parts from ocaml director.swg.
Add C++ 11 for newer compilers and improve platform independent.

2024-06-05 19:05 UTC, wsfulton commented
ping @erezgeva, can you address these small issues?

2024-06-07 18:12 UTC, erezgeva commented
> ping @erezgeva, can you address these small issues?

This pull request impleament #2861.

Do you mean to #2209?

I think my patch solve it.
On most Windows it will use C++ 11 std::mutex and with old Windows the CRITICAL_SECTION is encapsulate in a class.
But I do not have a Windows machine to test it.
I only use the GitHub actions with windows here.

Erez

2024-06-30 15:39 UTC, wsfulton requested changes

2024-06-30 15:40 UTC, wsfulton commented
> ping @erezgeva, can you address these small issues?

I was referring to my review comments, but they were still pending so you wouldn't have seen them! I've just posted them now, so sorry for the confusion.

2024-06-30 22:44 UTC, erezgeva commented on Lib/director_guard.swg
> +#define SWIG_GUARD_DEC(_mutex) static Mutex _mutex
Done

2024-06-30 22:46 UTC, erezgeva commented on Source/Modules/python.cxx
> +      Swig_insert_file("director_common.swg", f_runtime);
Fixed

2024-06-30 23:30 UTC, erezgeva commented on Lib/director_guard.swg
> + * Generic Mutex implementation
I try to improve description.

2024-07-02 07:54 UTC, merged

2024-07-02 08:05 UTC, wsfulton commented
I've added some docs in 5cfe3e7b3c656d395e530a445b782e4f4c25fbfd for my understanding of this. Please check. The threading was turned off by default in both Python and Ruby and now we have to defined `SWIG_THREADS` to turn the mutex locks on. We should have a test that tests `SWIG_THREADS`. Perhaps add a new test that includes an existing director test and test it on say just c++11:
```swig
%begin %{
#if __cplusplus >= 201103L
#define SWIG_THREADS
#endif
%}
```
But it would be good to have a testcase that replicates the original bug, but maybe that isn't easy to construct.

2024-07-02 14:03 UTC, erezgeva commented
> ```c++
> SWIG_THREADS
> ```

I tried to leave thing as their were.

In Ruby the mutex code is not used at the moment.
In python it is done with:
swig command line: 
`     -threads        - Add thread support for all the interface`
Source/Modules/python.cxx:
`    } else if (threads) {`
`      Printf(f_runtime, "#define SWIG_PYTHON_THREADS\n");`
Or using the `%thread` in the interface file.

A test is a good idea.
I'll try write one for python.
We could see that the C++ code define the Mutex.
May be print the class code result of `gcc -E` in the log ~20-30 lines?

As for the bug.
I do not have a Windows machine.
I think it is better to ask the person who found the bug and ask him to test.

2024-07-03 06:54 UTC, wsfulton commented
> A test is a good idea.
> I'll try write one for python.
> We could see that the C++ code define the Mutex.
> May be print the class code result of gcc -E in the log ~20-30 lines?

No need to add `gcc -E` output into the test, the test-suite doesn't handle that, however, checking this manually is a good idea. 

> As for the bug.
> I do not have a Windows machine.
> I think it is better to ask the person who report the bug and ask him to test.

Yes, that might be all we can do. I thought you saw a crash too and if you can replicate in a simple **runtime** test, then you can add that to the test-suite.

2024-07-03 14:55 UTC, erezgeva commented
> > A test is a good idea.
> > I'll try write one for python.
> > We could see that the C++ code define the Mutex.
> > May be print the class code result of gcc -E in the log ~20-30 lines?
> 
> No need to add `gcc -E` output into the test, the test-suite doesn't handle that, however, checking this manually is a good idea.
> 
> > As for the bug.
> > I do not have a Windows machine.
> > I think it is better to ask the person who report the bug and ask him to test.
> 
> Yes, that might be all we can do. You saw a problem too ("corrupted double-linked list" mentioned in #2861) and if you can replicate in a simple **runtime** test, then you can add that to the test-suite. With `SWIG_THREADS` defined in the test, it'll get tested on Windows (for Python) in the test-suite on Appveyor.

I add python also in #2813 win_ci.yml.

Regarding the "corrupted double-linked list", I saw. The problem was in my code, not SWIG.
I have a run condition between two destruction not created by SWIG,.
The run condition happens with my Ruby wrapper, and I was not sure.

I'll try write a test in python for this code.

2024-07-12 18:26 UTC, wsfulton commented
> I'll try write a test in python for this code.

Thanks for doing this (#2949).